import type { DashboardData } from "@/types/finance";

export const demoData: DashboardData = {
  userName: "Matheus",
  demoMode: true,
  reserve: 0,
  monthlyIncome: 480000,
  monthlyExpense: 283000,
  accounts: [
    {
      id: "inter",
      institution: "Inter",
      name: "Conta principal",
      type: "checking",
      balance: 443000,
      availableBalance: 443000,
      color: "#ff7a1a",
      lastSync: "Hoje, 12:42",
      status: "healthy",
    },
    {
      id: "nubank",
      institution: "Nubank",
      name: "Conta digital",
      type: "payment",
      balance: 185000,
      availableBalance: 185000,
      color: "#8a3ffc",
      lastSync: "Hoje, 12:39",
      status: "healthy",
    },
  ],
  creditCards: [
    {
      id: "nubank-card",
      institution: "Nubank",
      name: "Nubank Platinum",
      invoice: 124000,
      limit: 450000,
      availableLimit: 326000,
      closingDay: 28,
      dueDay: 5,
      color: "#8a3ffc",
    },
  ],
  people: [
    {
      id: "guilherme",
      name: "Guilherme",
      nickname: "Gui",
      avatar: "G",
      totalAssociated: 450000,
      received: 220000,
      pending: 230000,
    },
    {
      id: "roberto",
      name: "Roberto",
      avatar: "R",
      totalAssociated: 55000,
      received: 0,
      pending: 55000,
    },
  ],
  receivables: [
    {
      id: "rec-guilherme",
      personId: "guilherme",
      personName: "Guilherme",
      description: "Parcela da moto",
      total: 55000,
      received: 0,
      dueDate: "2026-08-30",
      status: "pending",
      installmentLabel: "5/10",
    },
    {
      id: "rec-roberto",
      personId: "roberto",
      personName: "Roberto",
      description: "Compra compartilhada",
      total: 55000,
      received: 0,
      dueDate: "2026-09-02",
      status: "pending",
    },
  ],
  payables: [
    {
      id: "rent",
      description: "Aluguel",
      amount: 120000,
      dueDate: "2026-09-01",
      status: "pending",
      recurring: true,
      category: "Moradia",
    },
    {
      id: "invoice",
      description: "Fatura do cartão",
      amount: 124000,
      dueDate: "2026-09-05",
      status: "pending",
      category: "Cartão",
    },
    {
      id: "bills",
      description: "Contas e assinaturas",
      amount: 42000,
      dueDate: "2026-09-08",
      status: "pending",
      recurring: true,
      category: "Serviços",
    },
  ],
  transactions: [
    {
      id: "tx-1",
      accountId: "inter",
      institution: "Inter",
      description: "Posto Avenida",
      merchant: "Posto Avenida",
      amount: -18590,
      date: "2026-08-25",
      category: "Combustível",
      categoryColor: "#f0a14a",
      nature: "expense",
      status: "posted",
    },
    {
      id: "tx-2",
      accountId: "nubank",
      institution: "Nubank",
      description: "Supermercado Krill",
      merchant: "Krill",
      amount: -32744,
      date: "2026-08-24",
      category: "Mercado",
      categoryColor: "#75c68f",
      nature: "expense",
      status: "posted",
    },
    {
      id: "tx-3",
      accountId: "inter",
      institution: "Inter",
      description: "PIX recebido Guilherme",
      amount: 55000,
      date: "2026-08-23",
      category: "Reembolsos",
      categoryColor: "#46b5a7",
      personId: "guilherme",
      personName: "Guilherme",
      nature: "debt_payment",
      status: "posted",
    },
    {
      id: "tx-4",
      accountId: "nubank",
      institution: "Nubank",
      description: "Netflix.com",
      merchant: "Netflix",
      amount: -5590,
      date: "2026-08-22",
      category: "Assinaturas",
      categoryColor: "#e56b79",
      nature: "expense",
      status: "posted",
    },
    {
      id: "tx-5",
      accountId: "inter",
      institution: "Inter",
      description: "Restaurante Caiçara",
      merchant: "Restaurante Caiçara",
      amount: -12480,
      date: "2026-08-21",
      category: "Alimentação",
      categoryColor: "#f2c14e",
      personId: "roberto",
      personName: "Roberto",
      nature: "shared",
      status: "posted",
      reimbursable: true,
    },
  ],
  cashFlow: [
    { label: "Mar", income: 420000, expense: 276000 },
    { label: "Abr", income: 420000, expense: 312000 },
    { label: "Mai", income: 465000, expense: 298000 },
    { label: "Jun", income: 440000, expense: 347000 },
    { label: "Jul", income: 480000, expense: 301000 },
    { label: "Ago", income: 480000, expense: 283000 },
  ],
  categories: [
    { name: "Moradia", amount: 120000, color: "#7d6df2" },
    { name: "Mercado", amount: 52400, color: "#75c68f" },
    { name: "Transporte", amount: 42600, color: "#f0a14a" },
    { name: "Assinaturas", amount: 23900, color: "#e56b79" },
    { name: "Outros", amount: 44100, color: "#7d8799" },
  ],
  timeline: [
    {
      id: "event-1",
      date: "2026-08-28",
      description: "Parcela do cartão",
      amount: 55000,
      kind: "expense",
      confirmed: true,
    },
    {
      id: "event-2",
      date: "2026-08-30",
      description: "Guilherme",
      amount: 55000,
      kind: "income",
      confirmed: false,
    },
    {
      id: "event-3",
      date: "2026-09-01",
      description: "Aluguel",
      amount: 120000,
      kind: "expense",
      confirmed: true,
    },
    {
      id: "event-4",
      date: "2026-09-05",
      description: "Receita prevista",
      amount: 240000,
      kind: "income",
      confirmed: true,
    },
  ],
};
